services:
  - type: web
    name: dsnow-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GEOAPIFY_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
